// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtdualnnfyeqdyidnzjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZHVhbG5uZnllcWR5aWRuempzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODUyMDcsImV4cCI6MjA2ODg2MTIwN30.EZ7YY7FUGa4aXMEUXSQu5hKEhTLr0N5dRXQmecaTMDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});